"""Initial migration

Revision ID: 20763577211a
Revises: 
Create Date: 2024-12-04 03:07:51.869574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20763577211a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Agregar los nuevos campos en la tabla 'ventas'
    op.add_column('ventas', sa.Column('total_productos_vendidos', sa.Integer(), nullable=True))
    op.add_column('ventas', sa.Column('total_costo_productos', sa.Float(), nullable=True))
    op.add_column('ventas', sa.Column('ganancias', sa.Float(), nullable=True))

    # Calcular el total de productos vendidos y el costo de los productos
    op.execute("""
    UPDATE ventas
    SET total_productos_vendidos = (
        SELECT SUM(d.cantidad)
        FROM detalles_venta d
        WHERE d.venta_id = ventas.id
    )
    """)

    op.execute("""
    UPDATE ventas
    SET total_costo_productos = (
        SELECT SUM(d.cantidad * p.precio)
        FROM detalles_venta d
        JOIN productos p ON p.id = d.producto_id
        WHERE d.venta_id = ventas.id
    )
    """)

    # Calcular las ganancias como la diferencia entre el total de ventas y el costo de productos vendidos
    op.execute("""
    UPDATE ventas
    SET ganancias = total - total_costo_productos
    """)

    # Modificar las nuevas columnas para hacerlas NOT NULL con valor por defecto 0
    op.alter_column('ventas', 'total_productos_vendidos', nullable=False, server_default='0')
    op.alter_column('ventas', 'total_costo_productos', nullable=False, server_default='0')
    op.alter_column('ventas', 'ganancias', nullable=False, server_default='0')



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalles_venta')
    op.drop_table('detalles_compra')
    op.drop_table('ventas')
    op.drop_table('compras')
    op.drop_table('users')
    op.drop_table('productos')
    # ### end Alembic commands ###
