"""Agregar campo total en ventas

Revision ID: 72e8a5dc1e98
Revises: a119f6a1c91a
Create Date: 2024-12-05 00:45:25.741430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72e8a5dc1e98'
down_revision: Union[str, None] = 'a119f6a1c91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
        # Eliminar la columna "total" existente (si es posible)

    op.add_column('ventas', sa.Column('total', sa.Float(), nullable=True))

    op.execute("""
    UPDATE ventas 
    SET total = (
        SELECT SUM(d.cantidad * d.precio)
        FROM detalles_venta d
        WHERE d.venta_id = ventas.id
    )
    """)

    # Modificar la columna 'total' para hacerla NOT NULL con valor por defecto 0
    op.alter_column('ventas', 'total', nullable=False, server_default='0')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ventas', 'total')
    op.alter_column('compras', 'total',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
