"""Añadir estado hab o deshab y ruta imagen al producto

Revision ID: e7cf79e792a1
Revises: d1d33a92dc13
Create Date: 2024-12-07 02:53:10.529762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7cf79e792a1'
down_revision: Union[str, None] = 'd1d33a92dc13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Verificar si la columna 'imagen' ya existe y, si no, agregarla
    try:
        op.add_column('productos', sa.Column('imagen', sa.String(length=255), nullable=True))
    except Exception as e:
        print("Columna 'imagen' ya existe:", e)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('productos', 'estado')
    op.drop_column('productos', 'imagen')
    # ### end Alembic commands ###
